### ISSUE TITLE
Host the sandbox docker automatically on push to main so that the system can automagically start using any bugfixes and updates

### ISSUE THREAD

**Issue by Joeoc2001** [AI-Wars-Soc/sandbox#2]
This issue concerns the automatic GitHub CI building and publishing of the Docker image

**Comment by jainris** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Host the sandbox docker automatically on push to main so that the system can automagically start using any bugfixes and updates](https://trello.com/c/3VPfi8Jw/15-host-the-sandbox-docker-automatically-on-push-to-main-so-that-the-system-can-automagically-start-using-any-bugfixes-and-updates)
